//
// Created by teeebor on 2017-09-05.
//

#pragma once

#define USAGE_PAGE(TYPE) 0x05, TYPE
#define USAGE_MINIMUM(MIN) 0x19, MIN
#define USAGE_MAXIMUM(MAX) 0x29, MAX
#define USAGE_MAXIMUM_SIM(MAX,P) 0x29, MAX, P
#define USAGE(TYPE) 0x09, TYPE
#define COLLECTION(TYPE) 0xA1, TYPE
#define END_COLLECTION 0xC0
#define REPORT_SIZE(SIZE) 0x75, SIZE
#define REPORT_COUNT(COUNT) 0x95, COUNT
#define REPORT(ID) 0x85, ID
#define LOGICAL_MINIMUM(MIN) 0x15, MIN
#define LOGICAL_MAXIMUM(MAX) 0x25, MAX
#define LOGICAL_MAXIMUM_SIM(MAX,P) 0x25, MAX, P
#define UNIT_EXPONENT(EXP) 0x55, EXP
#define UNIT(UNIT) 0x65, UNIT
#define INPUT_TYPE(TYPE) 0x81, TYPE
#define PHYSICAL_MINIMUM(MIN) 0x35, MIN
#define PHYSICAL_MAXIMUM(MAX, P) 0x46, MAX, P

#define GENERIC_DESKTOP 0x01
#define USAGE_JOYSTICK 0x04
#define COLLECTION_APP 0x01
#define USAGE_PAGE_BUTTON 0x09
#define USAGE_PAGE_SIM 0x02
#define COLLECTION_PHYSICAL 0x00
#define USAGE_THROTTLE 0xBB
#define USAGE_STEERING 0xBA
#define USAGE_POINTER 0x01
#define USAGE_HAT_SWITCH 0x39
#define UNIT_NONE 0x00
#define UNIT_ANG_POS 0x15
#define INPUT_DVA 0x02
#define LOGIC_BUTTON_UP 0x00
#define LOGIC_BUTTON_DOWN 0x01


/*#define JOYSTICK_REPORT_ID 0x03;
#define JOYSTICK2_REPORT_ID 0x04;
#define JOYSTICK_STATE_SIZE 4;


#define USAGE_PAGE 0x05;
#define USAGE 0x09;
#define COLLECTION 0xa1;
#define REPORT_ID 0x85;
#define REPORT_SIZE 0x01; //1
#define REPORT_COUNT 0x10;  //16
#define USAGE_MIN 0x19;
#define USAGE_MAX 0x29;
#define LOGICAL_MIN 0x15;
#define LOGICAL_MAX 0x25;

#define LOGICAL_MIN_VAL 0x00;
#define LOGICAL_MAX_VAL 0x01;

#define USAGE_MIN_VAL_BUTTON_1 0x01;
#define USAGE_MAX_VAL_BUTTON_16 0x10;

//USAGE PAGES
#define USAGE_PAGE_DESKTOP 0x01;
#define USAGE_PAGE_BUTTON 0x09;

//USAGE TYPES
#define USAGE_JOYSTICK 0x04;
#define USAGE_POINTER 0x01;*/
